#!/bin/sh

cat >&2 <<EOF

######################################################################
#### mina86/lets-nfsn.sh repository  is deprecated.   This script ####
#### does nothing (except for printing this message).             ####
####                                                              ####
#### Use  the  "official"  nfsn/lets-nfsn.sh  repository  instead ####
#### which you can find at <https://github.com/nfsn/lets-nfsn.sh> ####
######################################################################

EOF

exit 1
